name: Test1

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: install dependencies
        run: |
          brew install swiftlint
      - name: Cache carthage
        uses: actions/cache@v1
        with:
          path: Carthage
          key: ${{ env.DEVELOPER_DIR }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ env.DEVELOPER_DIR }}-carthage-
      - name: update node
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Run bootstrap script
        run: ./bootstrap.sh -ci
      - name: Run tests
        run: |
          set -o pipefail
          fastlane ios test
