name: essa

on: [push, watch]

jobs:
  test:
    name: test
    runs-on: macOS-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: install dependencies
        run: |
          brew install swiftlint
      - name: update node
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Run bootstrap script
        run: ./bootstrap.sh -ci
      - name: Cache carthage
        uses: actions/cache@v1
        with:
          path: Carthage
          key: carthage-${{ hashFiles('Cartfile.resolved') }}
      - name: Run tests
        run: |
          set -o pipefail
          fastlane ios test
